matrix:
  include:
    - env:
      - SELENIUM_BROWSER=chrome
    - env:
      - SELENIUM_BROWSER=firefox
os: trusty
services:
  - xvfb
addons:
  chrome: stable
  firefox: latest
sudo: false
language: node_js
node_js:
- '10'
cache: yarn
env:
  global:
  - NODE_ENV=development
  - secure: JvChxyhHnRpo9zWj5j/sZqK4gqZGmHZYHjfsbgbttE+kW2QXyvb0hDY962pn+Fx/v7D/pE0XoGnsaBWCXcaKna7IZYiweMJtXtbxcUmngBUbg1Xl6g0L1QH7YbCSDssfCtQ8vvssBrTURDCBDOwBNEuY4tqRY2amYYARrxPnaAgJOLPfHoLsTXNU0T4TnLmgIkpfXSuYalZHHVrDfnZbELOOCaBEc1C+sbFkVhpk6FgtcL4Aj4LgUjmISD6HRjkpEruZN7/ue8Eayq++ppFUviPVTc+qLbQYHJZ6+3j+QJMjj7mlivsQPgrX320g/NoRTH7dpOwOXKh1atAiccghLhy9Q1CjNCYEpgb2De8d9Q31LSIUFU7H2H2Ux8lUUyMGKq48licODjq2Ke/7abBFYofZoOUX8pFJ/CcVcDGfO+gIiVf1MLSC1vM3Otb1Z1/l4Y9f4Rhb4kKQH8FG+xxDRP4cJlzICAy7Km7Rz2joWVhJ8dxoswdGGw3fe4PYg/1aFbEkJvslZMVgUj58mkGPUBmLO+yCaCsqvHmJzVxzrQsbxYTbW5Ha56hZcw359+Ivth8LXqOxMoRn24ujRndJAc0Cw988rw0xRsOpUJOd+DML0i9oSfbhDlZ11KagZSg+JUTqgOvj58GICItaQRHJzhH0RUvuBht036MGZ8qYAhc=
  - secure: cFiC/NnOwrpU4xdLRDdvo8r6c29m0Q4t/c33pqv9LnxPzkOIu0tOwRaiP5YnzoNQSbB3PIcUs6ooIOT0TbKY4cZ+OkTHGWCGRTrnYT/KTLH6xG4S22kzAY+9337VVgo5teOkmC2Rk5aYVboHKdwRSWxtS5QBfHZp7myADEZg8wZTABerBCjJuo3kFRYhInxrnjrhgBk/8awOL6AGf2ZQ9j7NSPgAyOwTPsimIninsn23E8h8EZWMl3hw46i5zYD5mGsiJFoFxWBa5jxFFrrDHTpMUn1BhUnLyskqyiDVMspnSd1vFt/aAKsBU6EeypZD4hDKcB81BJeTM7JSrJRSWjinv3jXjW/DK5GTwAN+XUP5sviLmLCSApS7poH7bS2gf4V0wCRINcGmQgHOrN6s1zxDo/IkJ2Auv6SIK2MsPdjiWeLjDUbcBmGNyvMbW92u2dtOkKIMzJyuLfnPGixnzBiLTHFv2D0cTsh6BHCa9zXtkaNFVFYkVqqMQpoXGqGcCOcup86/YA3Su+Tz9VujTjE1gsrImg5rjDr2ri9nnG5hBGoZwORzv1BsIpVLHzTk1u11DK9ozU/g8MAzlG8KW3AL+DGGcdHtPxOZS9TTeN/oY2U1i50N7G8AIlyDNpaVn9KP+SNUTHEMkTgEGjam7Siyv+L0c5yx3t4pioJUumY=
  - secure: CQE5dHxC6JfnjkYalq0ecfzFeOqxbbPC+p6Fe6O9fId9fSDkg/7Y5L9mafkHHaucSTjWZLa1jlzU7teYy+tOb67BQG0N9gDafplKF7izbOSP5P9IqMzc5gO/HEzUo9J9eP3X3a/iWeHwgByg7+M3HxCxoIiCmmC2sWYg9Sf13O1ox//E4IwJmylhCCpgE0209vBHv/eKqU2UbH4darjkYQxoy2W/WShWTq4GhaOlju1iRxYIhJclFSU0Oe4uTMsyxb6F1kvkQAP27W87uwrr9QpxeOjwvq2Wna2WUTD5mrME6ZF5fWG/1fAmkBMURtfROModGZphCtlS19yFtJvZrx9fpa6nF6/gRwYa8YiZs5z6V/RBb8DvjZaxhxB0jxKLV0+ArSiNeO65hqOfBSNQM70pQKVvZwu/IcBjbB1EhoBcPB42fHEa6rzYtkLKoMzN318LsVGR2KiFNZJlL+TDQofl/HwV6iHJcfQ/5bybV6rIDCk6DW5ggYKenRIZGxr/KczZURCZStUhxz4ClhjunH5CdLiAcezB6XSmeW3BNyni8tEBqOGQW04NfaqhK85TeMuPIPU+vxjnRW/vwMSASLCy97VQl0lgt4UrIWlldluZtYXhzomd6XEqB08UeBt+pK0HXHf9Q8UxHDhBZh6YR4cLeac/DeemANhJM2YLbc4=
  - secure: n/Wh1murRSETkenzEoMZH29ex8EEW8RkI4gToI+tXjPTgHfVcfo1JqtaEltVAdjGAuUxsm6dQ70cAOCbKLGWWJBJA3Yr7Xx2ZtyRAdl70ZFxKr8uIv8UGr8767uKppehiayerXw47BInheo2lLEjKzdP1bvKsMz1pyc4B5ogLeUEkLDxCcpatQQRYDNsdbp8hPg0POOMe0AlgYkxnsqQBKbYbzw5WL1OrI8YLUH+yfM72lCRN5pHUQycngfuNEy24fjjrCKDbGW9J/vUiyUHHk3C71ryvNwLj87oMovf83g1PVoBWaVNkovr5AfD72BGaqkQfS8R2ZhgepO+1RtioSLiOcBdFDGBoOciIzghzzAZ0AVqb/vMML6a8+fSuaOVR/E9gF61hEsO9JWSEQzOODA8jNnYS2rtsAgo//yxw7nP5XUxuLW8x4ETeWAbTi2e8wAA6SxMkd9BDuPTwJcYzsgNoBjvhzVIPyK8k/OrXdntoZ7tJ/yqIjSinayvoXdBqvEXqImihYSVOjNhonabBFwtkFkG4AI/0KrWMN9t5OfTWGHLZDUzhOU8cMvc6ImIECUezLQ29R0RccKHVWCpYcaKds7KO3PymCOxAJRpueunc8aJoItdN6H7Gm44A03IpXtEWLuKsPer8OZcva2B+RT2GAAmyXTdjHEc0UrLbdw=
  - secure: pMQrudSyGJJso/QKRshBE033yBp+hpMRArgRqeJuPmJUt6OEmIMeM+oVmiIYz6ytYfvDYGOzVN2l4GUUiznQesC5ZcauduAKybN2mgQVdP7W1a/rQPcLuFGspR8k/pi+oAwvGcYjsWQXd5ukI+GZkxHVCFTPvJmDk/7amPsjPShaKQDnNjkTkiky2rAcdQN82pqDhlIQns5burK7kv+JuloyHCnGRfbQl2U8/88vMF6HmFtYBGiesYsgHXnJQ2mEn4wnamYGY+88RQmWeiqqaGi0He7yN+QgoFGgSksVlif1H8yOIStYkLNboAIN6rxaJc5m2x6tCtnpQby2nUITb1k5QP80LpidPZzUWWhE/dClXvZ/00S7XJS85MkS2hBtiA2/tsU15MhArgzq+28vQKLB2/aeGh2V3l/7gHgD3T2F477uCFUFTdzAkjkkrdpPvqBtRYCJvlOE/7u+TuMlJdEFhQsJzHooR4iVaspm/34nnW+GYLpd/Zfxka23qeSN8CStlV5ZT8kX275353g/iGC4wC3PdyuDUWHO9zLmcxvPNLQpXSqA0NlAOBC5Hg6x1rnndvH5nFiW+m2lsQ7zmUKip5J6yAxmMYhnRyPeWNpM0UsE99SHeqxTZexeUcsE7Q3Uwmu++FLKP+QPd0+Ec0Q2n6h4FnaQtxOkVl2vf3M=
  - secure: ENX9g8zCSS0cTQW7yeshMVuJaR1RbvKwG3KrCTqQDeGPK2Kp5Tj4Sctx8NjHgjadnnBHypab0E0/k7XxIP0sbHO1xB1r0p3LeEMZGTtaqGQph7AKcJulHVA2MYj7p6wKqc9ZEhWuHtFOdAIMiSAgxf6Rrz1+yIGKEpImoO4CeCekw/E7q4dF1zb4TuT3NpcacCUWtf18n4U/l0mdtKH5ewQ7LNfpraSnxetyDphsSK1d5s+g+RNMYs95bZL8CHg+NT4/4Efo0gz2o1aWj0nvI3x+zdggXTC0MchQ2YxCluXfGdLJ92WlRPG5CgalgauqAoQG7AzKkY3tNlIVgr0J0JAFQGvXCLDcLsjN0enR1QC2s+uMtlyw6hXePYc8Id9UkpBSNy5g8q5uKAhIUH3Ze6+yDCV33zOr2VGJcIRlU4fr/Mi8tamINcRDR5bZkIWN8QqrXeabINwrjS3pBsIdNBdDmH7HNRA41zKB+/nz9BYUaXc3cGDimzRt6tUMGp001XSjL+eUD+ib5bJjOn7oX3HPSO9qGv4Dq04g+otW2790mdS2ytXP+yqRUcaKjB84n8MYCOiumoREskSeJLftLHhkySFx5GaXgirr1uJzHjnrj7fKOyhjP1XlfweKapDXOoRkl7Y2SFUxuRPF5z1FGJbJOEDr1L+YnOd22kkslXA=
before_install:
- cp src/server/config.user.example.js src/server/config.user.js
- cp src/client/config.user.example.js src/client/config.user.js
- chmod ugo+x travis/get-webdrivers.sh
- travis/get-webdrivers.sh
- PATH=$PATH:$TRAVIS_BUILD_DIR
- echo $PATH
- geckodriver --version
- chromedriver --version
- echo $SELENIUM_BROWSER
install:
- yarn --frozen-lockfile --non-interactive
- yarn run build
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3 # give xvfb some time to start
- nohup yarn start &
- sleep 30 # give web-marbles server some time to start
